services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - app_logs:/app/logs

  db:
    image: postgres:17.2-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_EXPOSED_PORT}:5432"
    env_file:
      - .env

  redis:
    image: redis:7.2-alpine
    restart: on-failure
    volumes:
      - redisdata:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "${REDIS_EXPOSED_PORT}:6379"
    command: ["redis-server", "/usr/local/etc/redis/redis.conf", "--bind", "redis", "--port", "6379"]
    env_file:
      - .env

volumes:
  app_logs:
  pgdata:
  redisdata:
