"""add index for vacation

Revision ID: 3cc9bae11490
Revises: af89faaf5743
Create Date: 2025-01-28 00:24:27.613030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc9bae11490'
down_revision: Union[str, None] = 'af89faaf5743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_vacation_end_date', 'vacation', ['end_date'], unique=False)
    op.create_index('ix_vacation_start_date', 'vacation', ['start_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vacation_start_date', table_name='vacation')
    op.drop_index('ix_vacation_end_date', table_name='vacation')
    # ### end Alembic commands ###
