"""update all foreign keys

Revision ID: 8c54bf4a81fe
Revises: 3cc9bae11490
Create Date: 2025-01-29 03:51:40.854646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c54bf4a81fe'
down_revision: Union[str, None] = '3cc9bae11490'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('section_id', sa.Integer(), nullable=True))
    op.drop_index('ix_position_section_name', table_name='position')
    op.create_index('ix_position_section_name', 'position', ['section_id'], unique=False)
    op.drop_constraint('fk_position_section', 'position', type_='foreignkey')
    op.create_foreign_key('fk_position_section', 'position', 'section', ['section_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.drop_column('position', 'section_name')
    op.add_column('section', sa.Column('head_id', sa.Integer(), nullable=True))
    op.drop_index('ix_section_head_email', table_name='section')
    op.create_index('ix_section_head_email', 'section', ['head_id'], unique=False)
    op.drop_constraint('fk_section_user', 'section', type_='foreignkey')
    op.create_foreign_key('fk_section_user', 'section', 'user', ['head_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.drop_column('section', 'head_email')
    op.add_column('user', sa.Column('position_id', sa.Integer(), nullable=True))
    op.drop_index('ix_user_position_name', table_name='user')
    op.create_index('ix_user_position_name', 'user', ['position_id'], unique=False)
    op.drop_constraint('fk_user_position', 'user', type_='foreignkey')
    op.create_foreign_key('fk_user_position', 'user', 'position', ['position_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.drop_column('user', 'position_name')
    op.add_column('vacation', sa.Column('giver_id', sa.Integer(), nullable=True))
    op.add_column('vacation', sa.Column('receiver_id', sa.Integer(), nullable=False))
    op.drop_index('ix_vacation_giver_id', table_name='vacation')
    op.create_index('ix_vacation_giver_id', 'vacation', ['giver_id'], unique=False)
    op.drop_index('ix_vacation_receiver_id', table_name='vacation')
    op.create_index('ix_vacation_receiver_id', 'vacation', ['receiver_id'], unique=False)
    op.drop_constraint('fk_vacation_giv_user', 'vacation', type_='foreignkey')
    op.drop_constraint('fk_vacation_rev_user', 'vacation', type_='foreignkey')
    op.create_foreign_key('fk_vacation_giv_user', 'vacation', 'user', ['giver_id'], ['id'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_vacation_rev_user', 'vacation', 'user', ['receiver_id'], ['id'], ondelete='CASCADE', use_alter=True)
    op.drop_column('vacation', 'receiver_email')
    op.drop_column('vacation', 'giver_email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacation', sa.Column('giver_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('vacation', sa.Column('receiver_email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_vacation_rev_user', 'vacation', type_='foreignkey')
    op.drop_constraint('fk_vacation_giv_user', 'vacation', type_='foreignkey')
    op.create_foreign_key('fk_vacation_rev_user', 'vacation', 'user', ['receiver_email'], ['email'], ondelete='CASCADE')
    op.create_foreign_key('fk_vacation_giv_user', 'vacation', 'user', ['giver_email'], ['email'], ondelete='SET NULL')
    op.drop_index('ix_vacation_receiver_id', table_name='vacation')
    op.create_index('ix_vacation_receiver_id', 'vacation', ['receiver_email'], unique=False)
    op.drop_index('ix_vacation_giver_id', table_name='vacation')
    op.create_index('ix_vacation_giver_id', 'vacation', ['giver_email'], unique=False)
    op.drop_column('vacation', 'receiver_id')
    op.drop_column('vacation', 'giver_id')
    op.add_column('user', sa.Column('position_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_user_position', 'user', type_='foreignkey')
    op.create_foreign_key('fk_user_position', 'user', 'position', ['position_name'], ['name'], ondelete='SET NULL')
    op.drop_index('ix_user_position_name', table_name='user')
    op.create_index('ix_user_position_name', 'user', ['position_name'], unique=False)
    op.drop_column('user', 'position_id')
    op.add_column('section', sa.Column('head_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_section_user', 'section', type_='foreignkey')
    op.create_foreign_key('fk_section_user', 'section', 'user', ['head_email'], ['email'], ondelete='SET NULL')
    op.drop_index('ix_section_head_email', table_name='section')
    op.create_index('ix_section_head_email', 'section', ['head_email'], unique=False)
    op.drop_column('section', 'head_id')
    op.add_column('position', sa.Column('section_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('fk_position_section', 'position', type_='foreignkey')
    op.create_foreign_key('fk_position_section', 'position', 'section', ['section_name'], ['name'], ondelete='CASCADE')
    op.drop_index('ix_position_section_name', table_name='position')
    op.create_index('ix_position_section_name', 'position', ['section_name'], unique=False)
    op.drop_column('position', 'section_id')
    # ### end Alembic commands ###
