"""initial

Revision ID: a3fe7eec6d7c
Revises: 
Create Date: 2025-01-14 00:06:25.895588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3fe7eec6d7c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_name', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['section_name'], ['section.name'], name='fk_position_section', ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_position_name'), 'position', ['name'], unique=True)
    op.create_index('ix_position_section_name', 'position', ['section_name'], unique=False)
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('head_email', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['head_email'], ['user.email'], name='fk_section_user', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_section_head_email', 'section', ['head_email'], unique=False)
    op.create_index(op.f('ix_section_name'), 'section', ['name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('surname', sa.String(), nullable=False),
    sa.Column('position_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.Date(), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['position_name'], ['position.name'], name='fk_user_position', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_user_position_name', 'user', ['position_name'], unique=False)
    op.create_table('vacation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('giver_email', sa.String(), nullable=True),
    sa.Column('receiver_email', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['giver_email'], ['user.email'], name='fk_vacation_giv_user', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['receiver_email'], ['user.email'], name='fk_vacation_rev_user', ondelete='CASCADE', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vacation_dates', 'vacation', ['start_date', 'end_date'], unique=False)
    op.create_index('ix_vacation_giver_id', 'vacation', ['giver_email'], unique=False)
    op.create_index('ix_vacation_receiver_id', 'vacation', ['receiver_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_vacation_receiver_id', table_name='vacation')
    op.drop_index('ix_vacation_giver_id', table_name='vacation')
    op.drop_index('ix_vacation_dates', table_name='vacation')
    op.drop_table('vacation')
    op.drop_index('ix_user_position_name', table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_section_name'), table_name='section')
    op.drop_index('ix_section_head_email', table_name='section')
    op.drop_table('section')
    op.drop_index('ix_position_section_name', table_name='position')
    op.drop_index(op.f('ix_position_name'), table_name='position')
    op.drop_table('position')
    # ### end Alembic commands ###
