"""add is_active

Revision ID: f93916497163
Revises: a3fe7eec6d7c
Create Date: 2025-01-14 15:09:33.880181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f93916497163'
down_revision: Union[str, None] = 'a3fe7eec6d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_position_section', 'position', 'section', ['section_name'], ['name'], ondelete='CASCADE', use_alter=True)
    op.create_foreign_key('fk_section_user', 'section', 'user', ['head_email'], ['email'], ondelete='SET NULL', use_alter=True)
    op.add_column('user', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('is_verified', sa.Boolean(), nullable=False))
    op.create_foreign_key('fk_user_position', 'user', 'position', ['position_name'], ['name'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_vacation_giv_user', 'vacation', 'user', ['giver_email'], ['email'], ondelete='SET NULL', use_alter=True)
    op.create_foreign_key('fk_vacation_rev_user', 'vacation', 'user', ['receiver_email'], ['email'], ondelete='CASCADE', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_vacation_rev_user', 'vacation', type_='foreignkey')
    op.drop_constraint('fk_vacation_giv_user', 'vacation', type_='foreignkey')
    op.drop_constraint('fk_user_position', 'user', type_='foreignkey')
    op.drop_column('user', 'is_verified')
    op.drop_column('user', 'is_active')
    op.drop_constraint('fk_section_user', 'section', type_='foreignkey')
    op.drop_constraint('fk_position_section', 'position', type_='foreignkey')
    # ### end Alembic commands ###
